security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_provider:
            id: App\Security\UserProvider
        admin_user_provider:
            id: App\Security\AdminUserProvider

    encoders:
         Symfony\Component\Security\Core\User\UserInterface: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern: ^/admin
            form_login:
                provider: admin_user_provider
                login_path: admin_login
                check_path: admin_login_check
                username_parameter: "admin_login[username]"
                password_parameter: "admin_login[password]"
                csrf_parameter: "admin_login[_token]"
                csrf_token_id: "authenticate"
                csrf_token_generator: security.csrf.token_manager
                use_forward: false
                always_use_default_target_path: true
                default_target_path: admin_index
                use_referer: false
            logout:
               path: admin_logout
               target: /admin
               invalidate_session: true
            anonymous: true
        main:
            pattern: ^/
            form_login:
                provider: user_provider
                login_path: front_login
                check_path: front_login_check
                username_parameter: "user_login[username]"
                password_parameter: "user_login[password]"
                csrf_parameter: "user_login[_token]"
                csrf_token_id: "authenticate"
                csrf_token_generator: security.csrf.token_manager
                use_forward: false
                always_use_default_target_path: true
                default_target_path: front_index
                use_referer: false
            logout:
               path: front_logout
               target: /
               invalidate_session: true
            anonymous: true

    access_control:
          - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
          - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
